apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: new-pvc

spec: 
  storageClassName: manual
  volumeName: new-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi