apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-postgres
spec:
  storageClassName: "manual"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sf-postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      app: sf-postgres
  template:
    metadata:
      labels:
        app: sf-postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres:18.3-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: "Test123="
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        storageClassName: "manual"
        accessModes : ["ReadWriteOnce"]
        volumeName: pv-postgres
        resources:
          requests: 
            storage: 5Gi

